version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    build:
      context: .
      dockerfile: dockerfile_scraper_selenium
    volumes:
      - data_from_scrap:/scraper_app
    ports:
      - "4444:4444"
    shm_size: 2g
  
  mongodb:
    image: mongo
    build:
      context: .
      #dockerfile: dockerfile_mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=my_mongo
      - MONGO_INITDB_ROOT_USERNAME= user
      - MONGO_INITDB_ROOT_PASSWORD= user
    depends_on:
      - selenium-chrome
    volumes:
      - data_from_scrap:/tmp
    command: mongod --bind_ip_all --port 27017

  dash_app:
    build:
      context: .
      dockerfile: dockerfile_dash_app
    container_name: dash_app_container
    ports:
      - "8050:8050"
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: user
      MONGO_PASSWORD: user
      MONGO_DB_DATABASE: my_mongo
      MONGO_PORT: 27017
      
volumes:
  data_from_scrap:

