FROM mongo:latest

# Copiez le fichier JSON via le fichier de configuration de démarrage init-mongo.js depuis le volume vers le conteneur
COPY init-mongo.js /docker-entrypoint-initdb.d/

# Indiquez le nom de la base de données
ENV MONGO_DB_DATABASE=my_mongo

# Indiquez le nom de l'utilisateur MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=user

# Indiquez le mot de passe de l'utilisateur MongoDB
ENV MONGO_INITDB_ROOT_PASSWORD=user

# Exposez le port sur lequel MongoDB sera en cours d'exécution
EXPOSE 27017

# Exécutez la commande d'importation lors du démarrage du conteneur
CMD ["mongorestore", "--host", "mongodb:27017", "--db", "$MONGO_DB_DATABASE", "--username", "$MONGO_INITDB_ROOT_USERNAME", "--password", "$MONGO_INITDB_ROOT_PASSWORD", "/docker-entrypoint-initdb.d/"]


