FROM selenium/standalone-chrome:latest
# Le port 4444 est déjà exposé dans l'image par défaut

USER root

# Création du répertoire de travail
WORKDIR /scraper_app

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py

# Installation de pipenv
RUN pip install pipenv

# Copie des fichiers Pipfile et Pipfile.lock
COPY Pipfile Pipfile.lock /scraper_app/

# Installation des dépendances avec pipenv
RUN pipenv install --system --deploy

# Copie du reste des fichiers du projet
COPY data_collecting.py /scraper_app/

CMD ["pipenv", "shell"]
CMD ["scrapy", "runspider", "data_collecting.py", "-o", "data.json", "-t", "json"]